modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
    modId="projectdnd" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Project D&D" #mandatory
    logoFile="modlogo.png" #optional
    credits="N/A" #optional
    authors="Wagon, BoonelDanForever, Vik" #optional
    description='''
Descriptor

I
am
multi-
lined!

cool
'''

[[dependencies.projectdnd]]
    modId=""
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"